### ISSUE TITLE
Is there any idea about tackling the split / merge situation

### ISSUE THREAD

**Issue by ASONG0506** [Wolfwjs/GANet#9]
![Screenshot from 2022-05-09 17-21-21](https://user-images.githubusercontent.com/26050577/167381008-cc715b56-8da5-4c82-87aa-3d36083a7fba.png)

![Screenshot from 2022-05-09 17-20-31](https://user-images.githubusercontent.com/26050577/167381032-06613c38-efb4-409c-a245-dccbe2d1471d.png)

**Comment by ASONG0506** [comment]
thank you very much~

**Comment by Wolfwjs** [comment]
Hello, since there is no annotation for the split/merge type in CULane and TuSimple, we do not deal with this case separately. According to our test results, GANet can correctly predict the line near the vehicle for these cases.

As for these cases you show, you can try reducing `cluster_thr` in test config to shorten the clustering range, or retrain the model by redefining the starting points which are farther away.

**Comment by Wolfwjs** [comment]
Hello, since there is no annotation for the split/merge type in CULane and TuSimple, we do not deal with these cases separately. According to our test results, GANet can correctly predict the line near the vehicle for these cases.

As for the cases above, you can try reducing `cluster_thr` in test config to shorten the clustering range or retrain the model by redefining the starting points which are farther away.
